## 运行环境相关配置 ##

server.port: 8686




## 数据库相关配置 ##

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.0.219:3306/basecenter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true
  username: root
  password: iClassmate365Xyd